import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/components/ReduxProvider";
import ConvexClientProvider from "@/provider/clerk-convex-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sechat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" bg-gray-900 text-gray-100">
      <body className={inter.className}>
        <ConvexClientProvider>
          <ReduxProvider>
            <TooltipProvider>{children}
              <Toaster />
            </TooltipProvider>
          </ReduxProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
