import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ReduxProvider from "@/components/ReduxProvider";
import { ConvexClientProvider } from "@/provider/clerk-convex-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sechat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" bg-gray-900 text-gray-100">
<<<<<<< HEAD
=======
      <ClerkProvider>
>>>>>>> 64128c0cc990f297636df45721804704d4b9dadc
      <body className={inter.className}>
        <ConvexClientProvider>
        <ReduxProvider>{children}</ReduxProvider>
        </ConvexClientProvider>
      </body>
<<<<<<< HEAD
=======
      </ClerkProvider>
>>>>>>> 64128c0cc990f297636df45721804704d4b9dadc
    </html>
  );
}
